services:
    frontend:
        build:
            context: .
        image: tourism-front:latest
        env_file:
            - .env
        environment:
            ENV: prod
            BACKEND_BASE_URL: https://api.akyoltm.shop
            MEDIA_BASE_URL: https://api.akyoltm.shop
        ports:
            - "127.0.0.1:8081:8000"
        restart: unless-stopped
        networks:
            - tourism_tourism

networks:
    tourism_tourism:
        external: true
